### ISSUE TITLE
Is Develop the branch to submit PRs against

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/terraform-provider-solidfire#7]
https://github.com/solidfire/terraform-provider-solidfire#developing-the-provider doesn't mention which branch to use. It seems develop is the default here, not master like in some other SF and NetApp repos, but can the readme state that explicitly?

**Comment by cprokopiak** [comment]
Yeah, I'm not really sure why I had the previous repo using `develop` as the main branch. I've deleted that branch and only have master (now the default). Do you still want to have it called out explicitly to create PRs against the master branch in the README?

**Comment by scaleoutsean** [comment]
I'm okay with either implicit and explicit `master`. If there's only one "obvious" choice, most people should use that and won't attempt to submit against tagged branches. It appears most of SF repos accept PRs  to `master`.
So you could close this now that `develop` is gone.
